### ISSUE TITLE
Server never properly responds

### ISSUE THREAD

**Issue by freaktechnik** [WebThingsIO/webthing-java#29]
Sorry if this isn't actually an issue with this library and I'm just using it wrong - it's been a long time since I've written proper Java.

I've gotten to the point where I can start the web server. Doesn't matter if I start it as daemon or not or what route on the server I load, I always get the following errors for a single request:
```
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

This is with https://github.com/freaktechnik/Webthingify

Server is started here: https://github.com/freaktechnik/Webthingify/blob/master/app/src/main/java/be/humanoids/webthingify/ServerTask.java
Thing implementation is here: https://github.com/freaktechnik/Webthingify/blob/master/app/src/main/java/be/humanoids/webthingify/Phone.java

(most of the code is just glue between Android and the web thing library)

**Comment by mrstegeman** [comment]
The server tries to listen on port 80 by default, which isn't allowed by Android. Try listening on a different port. Try something higher, like 8080.

**Comment by freaktechnik** [comment]
I'm passing in 0 and it's choosing a random port number in the unassigned range (5 digits) according to its own reporting. I get the port here: https://github.com/freaktechnik/Webthingify/blob/master/app/src/main/java/be/humanoids/webthingify/ServerTask.java#L32

As I said, this error occurs when actually trying to load a path the server is serving, not in the setup.

**Comment by acris5** [comment]
Also got these errors on android. Thing became available after using real ip of device as hostname
server = new WebThingServer(new WebThingServer.SingleThing(busstop),
                               8889,ip_current);
But still can't make websockets working to pass events to gateway

**Comment by freaktechnik** [comment]
I figured out that the errors I posted here are happen on endpoints that the server is not explicitly serving.

There's also some issue with org.json from Abdroid not working with this lib.

**Comment by acris5** [comment]
>           I figured out that the errors I posted here are happen on endpoints that the server is not explicitly serving.
> There's also some issue with org.json from Abdroid not working with this lib.

I do not have this issue, what are you about?
